In [1]:
import bentoml
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
# Generate dummy dataset
X_train = np.random.rand(5,3)
X_test = np.random.rand(5,3)

In [3]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

### Save "scaler" object (model) with its functions "transform" and "inverse_tranform"

In [4]:
bentoml.sklearn.save_model("my_scaler", scaler,  signatures={ "transform" : { "batchable": False,}, "inverse_transform" : { "batchable": False,}})

Model(tag="my_scaler:kcqttpqwwcxktgxn", path="/Users/mehmettuncel/bentoml/models/my_scaler/kcqttpqwwcxktgxn/")

### Check the saved model using shell command on terminal (add prefix ! to commands)

In [5]:
! bentoml models list

 Tag                         Module           Size      Creation Time       
 my_scaler:kcqttpqwwcxktgxn  bentoml.sklearn  1.10 KiB  2023-06-29 22:08:21 


### Load "scaler" object (model) and test it

In [6]:
scaler2 = bentoml.sklearn.load_model("my_scaler:kcqttpqwwcxktgxn")

In [7]:
scaler.transform(X_test)

array([[-1.01035689,  4.96875791,  0.71955897],
       [ 0.93424069,  1.87191671,  1.24126084],
       [ 0.12545718,  2.07207713, -1.00459206],
       [-0.74500949,  3.09286156,  1.35088741],
       [ 1.02998804,  3.27607806, -0.88126629]])

In [8]:
scaler2.transform(X_test)

array([[-1.01035689,  4.96875791,  0.71955897],
       [ 0.93424069,  1.87191671,  1.24126084],
       [ 0.12545718,  2.07207713, -1.00459206],
       [-0.74500949,  3.09286156,  1.35088741],
       [ 1.02998804,  3.27607806, -0.88126629]])

### Model Import and Export
Models saved with BentoML can be exported to a standalone archive file outside of the model store for sharing. For example:

In [9]:
# list bentoml models saved
! bentoml models list

 Tag                         Module           Size      Creation Time       
 my_scaler:kcqttpqwwcxktgxn  bentoml.sklearn  1.10 KiB  2023-06-29 22:08:21 


In [10]:
# Export
! bentoml models export my_scaler:kcqttpqwwcxktgxn .

Model(tag="my_scaler:kcqttpqwwcxktgxn") exported to /Users/mehmettuncel/bentoml/denemeler/my_scaler-kcqttpqwwcxktgxn.bentomodel.


In [11]:
# Delete model from bentoml's models store
! bentoml models delete -y my_scaler:kcqttpqwwcxktgxn

Model(tag="my_scaler:kcqttpqwwcxktgxn") deleted.


In [12]:
# list bentoml models saved
! bentoml models list

 Tag  Module  Size  Creation Time 


In [13]:
# Import 
! bentoml models import ./my_scaler-kcqttpqwwcxktgxn.bentomodel

Model(tag="my_scaler:kcqttpqwwcxktgxn") imported.


In [14]:
# list bentoml models saved
! bentoml models list

 Tag                         Module           Size      Creation Time       
 my_scaler:kcqttpqwwcxktgxn  bentoml.sklearn  1.10 KiB  2023-06-29 22:08:21 


### Load it again and use

In [16]:
scaler3 = bentoml.sklearn.load_model("my_scaler:kcqttpqwwcxktgxn")

In [17]:
scaler.transform(X_test)

array([[-1.01035689,  4.96875791,  0.71955897],
       [ 0.93424069,  1.87191671,  1.24126084],
       [ 0.12545718,  2.07207713, -1.00459206],
       [-0.74500949,  3.09286156,  1.35088741],
       [ 1.02998804,  3.27607806, -0.88126629]])

In [19]:
scaler2.transform(X_test)

array([[-1.01035689,  4.96875791,  0.71955897],
       [ 0.93424069,  1.87191671,  1.24126084],
       [ 0.12545718,  2.07207713, -1.00459206],
       [-0.74500949,  3.09286156,  1.35088741],
       [ 1.02998804,  3.27607806, -0.88126629]])

In [20]:
scaler3.transform(X_test)

array([[-1.01035689,  4.96875791,  0.71955897],
       [ 0.93424069,  1.87191671,  1.24126084],
       [ 0.12545718,  2.07207713, -1.00459206],
       [-0.74500949,  3.09286156,  1.35088741],
       [ 1.02998804,  3.27607806, -0.88126629]])